query bookings($latitude: Float!, $longitude: Float!, $distance: Int!, $date: String) {
  bookings(geo: {latitude: $latitude, longitude: $longitude, distance: $distance}, date: $date) {
    edges {
      node {
        id
        date
        slot {
          id
          location {
            id
            latitude
            longitude
          }
          name
        }
        foodTruck {
          name
          description
          imageUrl
        }
      }
    }
  }
}
