{
  bookings {
    edges {
      node {
        date
        slot {
          location {
            latitude
            longitude
          }
          name
        }
        foodTruck {
          name
          description
        }
      }
    }
  }
}