{
  customerLocations {
    totalCount
    pageInfo {
      endCursor
      hasNextPage
    }
    edges{
      node {
        id
        location {
          id
          name
          latitude
          longitude
        }
        customer {
          id
          userName
          avatarUrl
        }
      }
    }
  }
}
